server:
  port: 8014
spring:
  application:
    name: cloud-cart-service
#    #这一块设置redis缓存配置
#  redis:
#    host: 192.168.56.10
#    port: 6379
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.tigerff.springcloud.commons.entities
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    fetch-registry: true
  instance:
    instance-id: cart8014  #在eureka那块显示的名字
    prefer-ip-address: true  # 当鼠标放在eureka那边名字上会在左下角显示ip地址

