server:
  port: 8000
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: goods8011 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8011   #匹配后提供服务的路由地址
          predicates:
            - Path=/goods/**   #断言,路径相匹配的进行路由

        - id: order8012
          uri: http://localhost:8012
          predicates:
            - Path=/order/**   #断言,路径相匹配的进行路由

        - id: cart8014
          uri: http://localhost:8014
          predicates:
            - Path=/cart/**   #断言,路径相匹配的进行路由

        - id: security8013
          uri: http://localhost:8013
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


